# Car Fuel Efficiency Analysis

This notebook analyzes the Car Fuel Efficiency dataset to answer several questions about fuel efficiency, vehicle properties, and statistical analysis.

## 1. Import Required Libraries

In [52]:
# Import necessary libraries
import pandas as pd
import numpy as np




## Q1: Pandas Version
Check the installed version of pandas.

In [3]:
# Check pandas version
pd.__version__

'2.2.3'

## Getting the Data
Download the Car Fuel Efficiency dataset and load it with Pandas.

In [4]:
# Download the dataset 
# You can use wget to download the file
# !wget https://raw.githubusercontent.com/bigdatadatafan/datasets-clase/main/car_fuel_efficiency.csv

# Load the dataset
df = pd.read_csv('data/car_fuel_efficiency.csv')
df
# After loading the data, let's take a look at the first few rows
# df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

## Data Exploration
Let's explore the dataset to understand its structure.

In [5]:
# Display basic information about the dataset
df.info()

# Get summary statistics
# df.describe()

# Check column names
# df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


## Q2: Records Count
Count the total number of records in the dataset.

In [60]:
# Count the total number of records
# Your code here
df.shape[0]

9704

## Q3: Fuel Types
Identify and count the different fuel types in the dataset.

In [7]:
# Find out how many fuel types are in the dataset
# Your code here
df['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

## Q4: Missing Values
Check for missing values in the dataset and count columns with missing values.

In [8]:
# Check for missing values in each column
# Method 1: Check total missing values per column
missing_values = df.isnull().sum()
print("Missing values per column:")
print(missing_values)

# Method 2: Count columns with at least one missing value
columns_with_missing = missing_values[missing_values > 0]
print("\nColumns with missing values:", len(columns_with_missing))
print("These columns are:")
print(columns_with_missing.index.tolist())

Missing values per column:
engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

Columns with missing values: 4
These columns are:
['num_cylinders', 'horsepower', 'acceleration', 'num_doors']


## Q5: Max Fuel Efficiency
Find the maximum fuel efficiency of cars from Asia.

In [9]:
# Filter cars from Asia and find the maximum fuel efficiency
cars_from_asia = df[df['origin'] == 'Asia']

# Find the maximum fuel efficiency
max_fuel_efficiency = cars_from_asia['fuel_efficiency_mpg'].max()
print(f"Maximum fuel efficiency of cars from Asia: {max_fuel_efficiency} mpg")

# Get the car with maximum fuel efficiency (for more details)
car_with_max_efficiency = cars_from_asia.loc[cars_from_asia['fuel_efficiency_mpg'].idxmax()]
print("\nDetails of the most fuel efficient Asian car:")
print(car_with_max_efficiency)

Maximum fuel efficiency of cars from Asia: 23.759122836520497 mpg

Details of the most fuel efficient Asian car:
engine_displacement                  330
num_cylinders                        3.0
horsepower                         136.0
vehicle_weight               1223.298226
acceleration                         NaN
model_year                          2001
origin                              Asia
fuel_type                       Gasoline
drivetrain             Front-wheel drive
num_doors                            1.0
fuel_efficiency_mpg            23.759123
Name: 9387, dtype: object


## Q6: Median Value of Horsepower
Calculate the median and most frequent value of horsepower, fill missing values, and check if the median changes.

In [ ]:
# 1. Calculate the median value of horsepower
# Nota: Para calcular la mediana deberías usar median() en lugar de mean()
median_of_horsepower = df['horsepower'].median()
print(f"Median value of horsepower: {median_of_horsepower}")

# 2. Find the most frequent value of horsepower
most_frequent_horsepower = df['horsepower'].value_counts().idxmax()
print(f"Most frequent value of horsepower: {most_frequent_horsepower}")

# 3. Fill missing values with the most frequent value
df_copy = df.copy()
df_copy['horsepower'] = df_copy['horsepower'].fillna(most_frequent_horsepower)

# 4. Calculate the new median
new_median_of_horsepower = df_copy['horsepower'].median()
print(f"New median is: {new_median_of_horsepower}")

# 5. Check if the median has changed
if median_of_horsepower != new_median_of_horsepower:
    print(f"The median has changed from {median_of_horsepower} to {new_median_of_horsepower}")
    print(f"Difference: {new_median_of_horsepower - median_of_horsepower}")
else:
    print("The median hasn't changed")

Median value of horsepower: 149.0
Most frequent value of horsepower: 152.0
Valores nulos antes: 708
Valores nulos después: 0
New median is: 152.0
The median has changed from 149.0 to 152.0
Difference: 3.0


## Q7: Sum of Weights
Implement linear regression calculation using matrix operations on selected data from Asian cars.

In [42]:
# 1. Select all cars from Asia
# Your code here
cars_from_asia = df[df['origin'] == 'Asia']
print(f"Cars from Assia:  \n{cars_from_asia.tail()}")

# 2. Select only columns vehicle_weight and model_year
# Your code here
specific_columns = cars_from_asia[["vehicle_weight", "model_year"]]
print(f"Showing the specific columns WEIGHT and MODEL \n{specific_columns}")


Cars from Assia:  
      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
9688            11.054830  
9692 

In [45]:
# 3. Select the first 7 values
# Your code here and 
firts_seven_values = specific_columns.head(7)
print(type(firts_seven_values))
firts_seven_values



<class 'pandas.core.frame.DataFrame'>


vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [50]:
# 4. Get the underlying NumPy array X
# Convertir el DataFrame a un arreglo NumPy y guardarlo en la variable X
X = firts_seven_values.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [51]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X
# Your code here
Y = X.T
Y

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [ ]:
# 6. Invert XTX
# Your code here
XTX = X.T @ X
print(XTX)
XTX_inv = np.linalg.inv(XTX)  # Inversa de la matriz XTX
print("Matriz inversa:", XTX_inv)



[[62248334.33150762 41431216.50732678]
 [41431216.50732678 28373339.        ]]
[[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]


In [57]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]
# Your code here
arr = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y = arr



In [ ]:

# Calcular los pesos de regresión lineal usando la fórmula w = (X^T·X)^(-1)·X^T·y
w = XTX_inv @ X.T @ y

# Mostrar los pesos calculados
w

Pesos de regresión lineal (w):
0.5187709081074007


In [ ]:

# 9. Calculate the sum of all elements in w
# Your code here
w.sum()

## Conclusion
Summarize your findings for each question.

In [ ]:
# Add your conclusions here after completing all questions
# Q1: The installed Pandas version is...
'2.2.3'
# Q2: The dataset contains...
"9704 records"
# Q3: There are...

# Q4: ...
# Q5: ...
# Q6: ...
# Q7: ...